### ISSUE TITLE
Render volumetric heatmaps on top of brain structures

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainrender#107]
Hi! This is a duplicate of an issue that I posted yesterday on the official vedo repository (https://github.com/marcomusy/vedo/issues/209). I wasn't sure anymore whether it fits best as separate brainrender or as a vedo issue (given that not all features of vedo are enabled in brainrender?). I think it is also similar to this issue: https://github.com/BrancoLab/brainrender/issues/105. 

What I want is to display some kind of volumetric heatmap, which I constructed as numpy array in the dimensions of the reference brain (allen 25 um), on top of some brain structures. 

```
actor = Volume(
        my_numpy_3d_volume,
        spacing=[25, 25, 25], 
        alpha=.5,
        alphaUnit=.5
    )
actor = actor.legosurface(vmin=np.nanmin(score_map)+0.25, cmap='inferno')
```
The `my_numpy_3d_volume` contains a bunch of scores (but mostly nans). I am able to utilise `.legosurface` to display the volume at the correct location, which is great. However, what I really want is some kind of "smooth point cloud" that is mostly transparent where the original volume contains nans. What happens when I use `.legosurface` is that I get a volume with pretty jagged edges which distracts from the actual information that I want to shine through (a smooth blob in the center). I can smooth the volume, but that also smoothes the values inside, which is not what I want. 
Do you have any tipps on how to do this kind of stuff?

**Comment by FedeClaudi** [comment]
Hi,

The 'jaggedness' of the mesh you get with `.legosurface` is inherent to the fact that you have volumetric data with 25um voxels. The most straightforward way to smoothen it would be to increase the resolution of your raw data, if possible. 
It might even be possible to upscale with interpolation `my_numpy_3d_volume` directly (with numpy or sklearn). This would also yield a higher resolution volume so that the 'blocks' youg et out of `legosurface` are smaller and the overall look is smoother. 

There's also a few vedo issues on volumens that might be helpful:
* https://github.com/marcomusy/vedo/issues/147
* https://github.com/marcomusy/vedo/issues/150
* generate surface mesh from volume: https://github.com/marcomusy/vedo/issues/113


In general, directly visualizing volumes in `brainrender` is not something I've done much of because I never had that kind of data. Even for things like [visualizing gene expression](https://docs.brainrender.info/overview/examples#visualizing-datasets-from-the-allen-institute) I've only done `legosurface` as I was happy with that: I like how it reflects the fact that the data is produced in voxels of a given size. 
So if you find a better way to deal with these things in `brainrender` please let me know, or send a PR :)

**Comment by horsto** [comment]
Thanks I will look into that. Quick follow-up though: With legosurface is it possible to render parts that are nan transparent? I could maybe substitute the values and then play with `vmin` (?), but is there a better way? Also, is it somehow possible to get rid of the boundaries between blocks in legosurface such that adjacent block boundaries are not actually visible? That would already help a lot I think.

**Comment by FedeClaudi** [comment]
[this](https://github.com/BrancoLab/brainrender/blob/4c087bc4cb8f94ba394dc0cf75baa646065ea44b/brainrender/ABA/gene_expression/api.py#L214) is how I do it for gene expression data. I don't know how it works with `nans` but yeah you can convert them to some numeric value before thresholding if that's causing you problems. 

I haven't played around with it, but you might be able to change the appearance of the mesh you get from lego surface. 
In vedo when legosurface is created:
https://github.com/marcomusy/vedo/blob/c8d5b3fcdeea49a89e74f3b4dd9dc86d7c08b42e/vedo/base.py#L1428

it sets `lw` to `0.1`, which I think it's why you see the voxels edges. You can try to do `.lw(0)` to see if that works.

**Comment by marcomusy** [comment]
In principle (not so well tested..) it should work with `nan` too, check out example
`vedo -r mesh_lut`

**Comment by enassar** [comment]
Hey! So I'm working on a similar visualisation using legosurface, but I'm having some issues with alpha. This is what my data looks like with these two lines of code:

`actor = load_mesh_from_file('path/to/data')`
`tmap = actor.legosurface(vmin=0.00001, cmap='jet').lw(0).lighting('off')`

![Screenshot 2020-09-21 at 14 03 56](https://user-images.githubusercontent.com/59826370/93770179-c6e9a300-fc13-11ea-9938-69acad37101c.png)

But I want to look at what's going on inside. At first I wanted to set a gradual increase in alpha with increasing voxel value, but legosurface doesn't accept that. I tried applying this on the mesh before inputting the mesh into legosurface, but that didn't work either. Then I just added `.alpha(0.3)` to legosurface, and this is what I get:

![Screenshot 2020-09-21 at 14 13 56](https://user-images.githubusercontent.com/59826370/93772698-09f94580-fc17-11ea-9f51-9f06175762e3.png)

The heatmap turns into a shell, where colour is still visible on the surface but not inside. Do any of you know why this is the case?

@horsto I am curious to know what you ended up doing!

Thanks :)

**Comment by FedeClaudi** [comment]
Hi,

That looks cool!

@marcomusy  might correct me if I'm wrong, but I think that `legosurfaces` creates a mesh representing the surface of the thresholded volume. That's why you only see the `outer shell`. 

If you want to be able to inspect the inside of the volume perhaps doing something like [vedo's Slicer](https://github.com/marcomusy/vedo/blob/2b585cb9993f0fe0aa394421fc237dd7550aecb2/examples/advanced/slicer1.py) functionality is the best solution.

**Comment by marcomusy** [comment]
@FedeClaudi correct!

One other trick to see the inside is to transform the volume into a mesh, eg.:
```python
from vedo import *
vol = load(datadir+'embryo.tif')
msh = vol.tomesh().clean()
msh.cutWithPlane(origin=(14000,0,0), normal=(1,1,1)).cmap('gist_ncar')
show(vol, msh, N=2, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/93836103-d69fd080-fc81-11ea-8dee-1c006ee85d3e.png)

Note that this is feasible if the volume is relatively small.

**Comment by FedeClaudi** [comment]
hi @enassar and @horsto  just checking in to see if in the end you've found a solution you're happy with for these problems.

**Comment by horsto** [comment]
Thanks @FedeClaudi and sorry for my absence from this thread. My problem was slightly different than the one from @enassar. I ended up just creating a little volume at the place I wanted it to show and "cut it in place" by applying region and layer boundaries. This worked fine for the figure I wanted to generate (since I rotated it so the bird's eye view just showed it exactly how I wanted).

**Comment by FedeClaudi** [comment]
Hey @horsto, brainrender has a new 'Density' kind of visualization: 
![image](https://user-images.githubusercontent.com/17436313/101086347-a2f9f480-35a8-11eb-9c00-6f4bdcaf2393.png)

It might not be exactly what you needed, but perhaps worth having a look

**Comment by horsto** [comment]
This looks extremely cool @FedeClaudi! Thanks a lot for pointing this out. It seems to be almost exactly what I wanted.

**Comment by harshk95** [comment]
Hi,
I wished I have a similar use case and wanted to ask how I can implement the 'Density' visualization in Brainrender.
Any pointers would be greatly appreciated!

Thanks!

**Comment by FedeClaudi** [comment]
There's an example showing how to visualize density data in brainrender: https://github.com/brainglobe/brainrender/blob/master/examples/cell_density.py

**Comment by harshk95** [comment]
Thanks a lot @FedeClaudi 
When I run the example code, I get the following ouput which is different from what I wouldve expected.

![image](https://user-images.githubusercontent.com/42764867/143590674-4ee7b40d-ff52-415d-99f4-4bb2ebf33be8.png)

I was wondering what might be going wrong.

Thanks again!

**Comment by harshk95** [comment]
Hi, 
just an update that I tried using different versions of python (both 3.6 and 3.7) and both installing using pip install brainrender and the installation from the latest cloned github repository and still get this issue.
Thanks for the help.

**Comment by FedeClaudi** [comment]
Seems to be something with vedo: I'm following up on this here: https://github.com/marcomusy/vedo/issues/547

**Comment by FedeClaudi** [comment]
Under discussion at: https://github.com/brainglobe/brainrender/pull/182
