### ISSUE TITLE
Run all example scripts in tests

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainrender#109]
This might be a convenient way to ensure everything demonstrated in the examples work, and to provide additional, if silent, coverage to the testing. In the most simple way it can be done just with terminal commands in the .sh shell script I think.

**Comment by FedeClaudi** [comment]
Hey,

It's a good idea and I initially thought of doing that, but there's a problem.
`scene.render()` blocks the program execution, that's why [in tests](https://github.com/BrancoLab/brainrender/blob/4c087bc4cb8f94ba394dc0cf75baa646065ea44b/tests/test_scene.py#L69) I always call it with `interactive=False`. 

So if I were to run the examples as `.py` files the tests would block... 
I don't know if there's a way to auto-detect if a script is being called in tests to automatically set `interactive=False`?

**Comment by vigji** [comment]
uhm...maybe you can have an INTERACTIVE global parameter that can be set and stored in the configuration file?

**Comment by FedeClaudi** [comment]
I've added to a script to run the examples, but won't include that in tests.
