### ISSUE TITLE
Trying to load in NIFTI images

### ISSUE THREAD

**Issue by mabbasi6** [brainglobe/brainrender#135]
Hi,

I have been trying to visualize some mouse brain data which are registered to Allen Brain Template and are in NIFTI format. When I try to load them using the script, I get this error "ValueError: axes don’t match array". So, I tried to load the Allen Brain Template (100 um data), and it didn't give any error but nothing showed up. Using GUI, I don't get any errors, but nothing gets added to the scene, I just choose the file and select it and then, nothing.
I suspect there are steps for loading NII I am missing? Or any requisites my data might have that is missing?

Best,
Momo

**Comment by FedeClaudi** [comment]
Hi, 

The GUI can't load from .nifti files yet, only from mesh files (e.g. obj), but you should be able to get it to work  without the gui.
The steps are

1. load the nifti file, this should result in a 3D numpy array
2. turn the numpy array into a Volume actor
3. add actor to the scene and render

The [Volume](https://github.com/brainglobe/brainrender/blob/master/brainrender/actors/volume.py) actor class can render your data either as a mesh surface or as a volume object, in your case the volume option might be the best to start with, so you pass `as_surface=False` when creating the volume. You can look at this example on [volumetric data](https://github.com/brainglobe/brainrender/blob/master/examples/volumetric_data.py) to try things out. 

I'm not sure where your error is coming from though. Would you mind sharing the code you're using and perhaps more details about your error (e.g. what line is causing it etc.).

**Comment by mabbasi6** [comment]
Hi,

Thanks for your response. I'll be only using the script then.
I have attached a screenshot that shows the code I'm using and the error.

Momo
<img width="1615" alt="Screen Shot 2020-12-09 at 11 34 40 AM" src="https://user-images.githubusercontent.com/75707223/101672663-651b2700-3a13-11eb-804a-b9411fcf1648.png">

**Comment by mabbasi6** [comment]
Adding some changes to the code, same error persists:
<img width="1614" alt="Screen Shot 2020-12-09 at 11 42 21 AM" src="https://user-images.githubusercontent.com/75707223/101672862-9e539700-3a13-11eb-9066-9879a85f0db2.png">

**Comment by FedeClaudi** [comment]
Okay, the first thing that I'd ask you to do is to switch from `brainio` to [`imio`](https://github.com/adamltyson/imio), I know I suggested you'd use `brainio` but `imio` does pretty much the same stuff and it's still maintained by @adamltyson  (while `brainio` is not maintained anymore).
So after `pip install imio` you can replace your second line with:
```python
from imio import load
```
and load the data with
```python
data = load.load_any(xx)
```

This is not going to fix the problem but it's a start. 
The problem seems to be doing a transpose operation on the numpy array on you data (inside of `vedo`'s `Volume` class).
So the first thing you should do is to make sure that `data` is what you'd think it should be: look at the size, number of dimensions etc. 

By the way if you are using Jupyter notebooks please make sure to check the [docs on notebooks](https://docs.brainrender.info/usage/using-notebooks) and the relevant examples.
Also, when using `brainrender` not in notebooks it relies on [pyinspect](https://github.com/FedeClaudi/pyinspect#when-you-cant-fix-that-bug) to give more informative error messages with details about the variables in the error line, like this:
![image](https://user-images.githubusercontent.com/17436313/101681504-20ff4500-3a5a-11eb-882a-deb7bcf95801.png)

That is generally very useful especially when the error message doesn't give any detail like in this case

**Comment by mabbasi6** [comment]
I applied the changes you suggested, and also loaded the Allen Brain Annotation file (100 um), which worked this time and the data can be seen in the scene. However, I'm noticing that the orientation of the file is different from the transparent background brain in the scene (the data is rotated as you see in the screenshot), so I was wondering how I could modify that.

For my own dataset, I tried running on Python instead of Jupyter and still got the same error. I have attached my NIFTI file in case you would like to check what could be wrong with that. This data is registered to Allen Brain Template and the resolution is 100
[jac_100pos_mask.nii.zip](https://github.com/brainglobe/brainrender/files/5668711/jac_100pos_mask.nii.zip)
 um.
<img width="1124" alt="Screen Shot 2020-12-09 at 2 04 01 PM" src="https://user-images.githubusercontent.com/75707223/101688219-ef21ba80-3a28-11eb-9bf0-03391186edc0.png">


.

**Comment by FedeClaudi** [comment]
Thanks for sending the data, that helps. This is what it looks like for me:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/101691163-34181200-3a66-11eb-8bbf-4cffffc03d59.png">

with
```python
from brainrender import Scene  
from brainrender.actors import Volume

from imio import load

data = load.load_any('/Users/federicoclaudi/Downloads/jac_100pos_mask.nii')

print(data.shape)

scene = Scene(title='Data')
scene.add(
    Volume(
        data,
        voxel_size=100,
        as_surface=False,
    )
)
scene.render()
```

The fact that the data is rotate is not a brainrender issue, it will depend on how your data was created, registered to a reference atlas etc. In order to align the data to the atlas used in brainrender you will have to do some operations on your data.
Brainglobe has [bg-space](https://github.com/brainglobe/bg-space) that helps with that. 

For instance the following code rotates the brain:
```python
from brainrender import Scene  
from brainrender.actors import Volume
from bg_space import AnatomicalSpace



from imio import load

data = load.load_any('/Users/federicoclaudi/Downloads/jac_100pos_mask.nii')

print(data.shape)

scene = Scene(title='Data')


source_space = AnatomicalSpace("rai")
target_space = scene.atlas.space
transformed_stack = source_space.map_stack_to(target_space, data)

scene.add(
    Volume(
        transformed_stack,
        voxel_size=100,
        as_surface=False,
    )
)
scene.render()
```

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/101691633-e354e900-3a66-11eb-9ed9-6a722114dcf8.png">

but it's rotated wrong, you'll want to set `AnatomicalSpace` to be using the origin as it's defined in your original data and then you can use that to transform your data correctly. For more reference check https://github.com/brainglobe/bg-space

**Comment by mabbasi6** [comment]
Great! Now I just need to modify the orientation to make it compatible with the brainrender.
I figured the problem with the other dataset was that it had sub-bricks, so removing them solves the problem of the axes match.
Your help has been great! Thanks!
Can the visualization be modified in terms of color, or the theme (like cartoon style)?

**Comment by FedeClaudi** [comment]
Excellent!
Yes you can. With `as_surface=False` the data are shown as a `vedo.Volume` class: https://github.com/marcomusy/vedo/blob/af7553dc04283e001cb03f910cfaf00f4682eb86/vedo/volume.py#L231

This has several options for determining its aspect, e.g. you can color it with a different colormap.
If you want your data to look like this:
![image](https://user-images.githubusercontent.com/17436313/101748048-f518a980-3ac3-11eb-848b-d98a3034d915.png)

then you need to set `as_surface=True`, this will threshold your data and. extract a lego surface, you will need to specify the threshold value. I haven't tried, but I think that 
```python
vol =    Volume(
        transformed_stack,
        voxel_size=100,
        as_surface=False,
    ).isosurface()
scene.add(vol)
```
would also give a surface

**Comment by FedeClaudi** [comment]
I'll close as the original issue is addressed but get in touch with any question. 

By the way, `braindern`'s `Volume` class is a thin wrapper around `vedo.volume.Volume` so if you want to learn more about how to change the appearance of your data you might want to play around with vedo first.
