### ISSUE TITLE
Loading NIFTI and exporting as HTML

### ISSUE THREAD

**Issue by mabbasi6** [brainglobe/brainrender#137]
Hi Federico,

Thanks for the previous help you provided with loading the NIFTI data.
When I run the code and the render opens in a new page, the visualization looks great inside the mouse brain. 
However, when I export the same code as HTML, the NIFTI data is visualized out of the brain as a shadow, but brain regions are inside it. Just the NII data is out of the brain.
I have attached the HTML file, the code and data for your attention.
[issue.zip](https://github.com/brainglobe/brainrender/files/5692389/issue.zip)

Best,
Momo

**Comment by FedeClaudi** [comment]
Hey, 

thanks for the detailed report that makes things so much easier. 
I've isolated the issue but not sure how to fix it. 

After [long discussions](https://github.com/brainglobe/bg-atlasapi/issues/73) with the other brainglobe developers we've decided to apply a transform to brainrender's scene such that the orientation of the axes in brainrender matches what you get in other software (e.g. napari, used extensively by cellfinder and brainreg). 
That's because if we didn't, then you'd get weird stuff like something that you know was in the right hemisphere, that you see in the right hemisphere with other software, appears to be in the left hemisphere in brainrender.

To fix this, brainrender [applies a transform](https://github.com/brainglobe/brainrender/blob/ad524f9e10898492ff8aeb1f31c69bf43b4f6d3c/brainrender/render.py#L103) to each actor before rendering.

This is half of the problem, the other half is that before exporting a scene to HTML, brainrender re-creates it in a new vedo Plotter using [k3d](https://github.com/brainglobe/brainrender/blob/ad524f9e10898492ff8aeb1f31c69bf43b4f6d3c/brainrender/render.py#L230) as backend. K3d is a bit limited and doesn't support all vtk functionality, upon which brainrender normally relies. 

So, what  I think is happening is that the 'transform' operation on the volume (but not on the meshes) is not working when exporting with k3d. So you end up seeing all meshes 'transformed' and the volume not transformed. Because your data is symmetric this looks like the volume is just in the wrong position, but it's actually mirrored left to right.

To confirm that this is the case, I've tried exporting your scene but after having disabled the code that applies the transformation: 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/17436313/102198118-ebbf8080-3eb9-11eb-92c6-df54f93fa556.png">

now meshes and volume are in register, but they are in the 'wrong' orientation. 

So I think that you can't export volumes to HTML unfortunately. I'm not sure how to best handle this in branirender, perhaps brainrender can detect when a Volume is in the scene, warn the user, and transform it to a surface mesh before exporting?

**Comment by mabbasi6** [comment]
Thank you for the prompt response.

Is there any other sort of export you would recommend? (For now, I am using screenshots from the popup scene)
I would like to use these visualization as a reporting tool to my collaborators.

Best,
Momo

**Comment by FedeClaudi** [comment]
Screenshots and videos are the solid, the HTML export is a bit finicky because of K3D. I think perhaps for now the best option is to either export to HTML but with the volume rendered as a scene, or to provide a jupyter notebook where people can easily run the code they need. Though that. requires having brainrender/python installed etc.

Alternatively, if you do want to export to HTML with the volume, you'd need to disable the 'transform' operation. I'm not going to implement this as it's not something that I would want users to mess around with, but if you fork brainrender's repository you can easily make that happen and then you can install brainrender from your repository.

**Comment by mabbasi6** [comment]
So, I disabled the transform operation and saved it as another repository.
I would like to use the functionality of VTK, is there a way of exporting the scene as VTK?

**Comment by FedeClaudi** [comment]
The transform is there for a reason though, everything will be inverted left to right compared to other software you might use to inspect your data without it. 

I'm not sure what you mean for exporting the scene as vtk? `vedo` supports various methods to export single actors and whole scenes you might want to look into that

**Comment by FedeClaudi** [comment]
Hi, @mabbasi6  just following up on this. Is everything resolved or are there some more issues to address?

**Comment by mabbasi6** [comment]
Hi, my teammate @crsanderford has been working on this issue and has modified the transformation matrix and got it to work. I asked him to join our conversation and share that with you.

**Comment by crsanderford** [comment]
Hi Federico - it seems as though when you keep the transform operation but change the matrix to an identity matrix, the export image is in the proper orientation and in register. The out-of-register issue also doesn't seem to be limited to html exports - when we used vedo's write function to produce vtm files, these too were out-of-register if the original matrix was used for rendering, but back in register when the identity matrix was used.

I have a branch on our repository that allows passing of matrices; I'll prepare a script to demonstrate this shortly.

**Comment by FedeClaudi** [comment]
Hi, I see. It seems that the issue might be internal to vedo (cc @marcomusy ) then, as if the transform is only applied for visualization and not for exporting data when using volumes. 

My only issue with using the identity matrix is that the transform is there for a reason: brainrender's default axes are oriented differently from other software (e.g. napari) so that the two hemisphere's are mirrored. Something that would be in the left hemisphere, that you'd see in the left hemisphere in napari, would look like it's in the right hemisphere if the transform wasn't there.  Your data looks fairly symmetrical, so in your case it doesn't matter if the data looks mirrored, but it is not a good general solution. Will have to think about how to best solve this.

**Comment by crsanderford** [comment]
I stand corrected - it seems like exported files are mirrored regardless of the choice of matrix.

Rendered with the normal transformation matrix, first is rendered, second is exported to .vtm and then displayed in vedo.

![brainrender_render_normal_mtx](https://user-images.githubusercontent.com/50089673/107105290-b745b200-67e2-11eb-9fd0-fe7ef98a46e9.png)
![brainrender_export_normal_mtx](https://user-images.githubusercontent.com/50089673/107105087-da239680-67e1-11eb-99e8-f9cd7f441cb0.png)

And rendered with the identity matrix, first is rendered, second is exported to .vtm.
![brainrender_render_identity_mtx](https://user-images.githubusercontent.com/50089673/107105086-d859d300-67e1-11eb-80b2-30fe7e5ba216.png)
![brainrender_export_identity_mtx](https://user-images.githubusercontent.com/50089673/107105085-d7c13c80-67e1-11eb-9afc-4553ea891a4f.png)

**Comment by FedeClaudi** [comment]
yeah, something weird is going on, but it really seems to be internal to `vedo`. Just to check, for these particular data would you expect to see the meshes in the right or left hemisphere?

Being a vedo related issue I fear there's not much I can do here, except maybe add a warning when users try to export a `vedo.Volume` object? 

Could you try two things for me:
1. convert the volume actors to surface meshes (e.g. `Volume.legosurface`, vedo has several methods to do this) and see if exporting those is fine (it should be). 
2. Can you try appluying the transform matrix, then exporting, then loading the data back in and applying the transform matrix again to just the volume actor? Does that put it back in the right place?

**Comment by crsanderford** [comment]
> for these particular data would you expect to see the meshes in the right or left hemisphere?
I set data with a z-position greater than the central value to zero, which matches with the axis marks in the first image - I believe seeing data only in the right hemisphere is correct.

> convert the volume actors to surface meshes (e.g. Volume.legosurface, vedo has several methods to do this) and see if exporting those is fine (it should be).
The isosurface method definitely does work appropriately both for rendering and exporting, yep!

![render_isosurface](https://user-images.githubusercontent.com/50089673/109099339-2b87bd00-76e0-11eb-8244-fa8c063c9396.png)
![export_isosurface](https://user-images.githubusercontent.com/50089673/109099333-29bdf980-76e0-11eb-87ee-0d821acbec49.png)

>  applying the transform matrix, then exporting, then loading the data back in and applying the transform matrix again to just the volume actor? Does that put it back in the right place?

This works as well!
![export_retransform](https://user-images.githubusercontent.com/50089673/109101602-44926d00-76e4-11eb-915d-b9ecb5163775.png)

**Comment by FedeClaudi** [comment]
Awesome!
