### ISSUE TITLE
GUI - Improvements

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainrender#145]
Listing some improvements to the GUI functionality that contributors might be interested in collaborating on. 

## Simple
* Adding `Volume` actors from .npy files
* When adding cells, let users select if the want a `Points` or `PointsDensity` actor
* More optional arguments for CLI (e.g. shader, background color etc)

## Intermediate
* general code clean up / UI improvments

## Advanced
* Video record functionality: register what happens to the scene while user interacts with it and save to frame, then build a video out of it.

**Comment by FedeClaudi** [comment]
See https://github.com/brainglobe/brainrender/issues/164 and https://github.com/brainglobe/brainrender/issues/165

**Comment by francesshei** [comment]
Hey @FedeClaudi! 
I played around with PyQt and brainrender and I think I found what causes the extra-window to pop-up when opening an application with the brainrender widget. 
From what I see, the problem is that the Scene initialization (line 40 in app.py) calls the Render class which in turn is initialized with "the standard" Vedo plotter: even though the plotter is then changed to the vtkWidget with the `setup_plotter` function, there is still a part of the code that opens the default window. 
I managed to solve the bug by using locally modified Scene and Render classes and initializing a vtkWidget before the scene class to pass the custom plotter as extra argument: 
>` new_plotter = Plotter(qtWidget=self.vtkWidget)`
  `self.scene = Scene(*args, atlas_name=atlas_name, inset= False, plotter=new_plotter, **kwargs)`

This also  eliminated the need of an "intermediate" App class to render the widget resulting in a more "PyQt-esque" implementation, in which the main function intializes a QMainWindow (and not the App class) with the vtkWidget directly displaying the brainrender scene (might be useful in cleaning / reducing the code).

**Comment by francesshei** [comment]
PS: this workaround also fixed the system-wide mouse/keyboard input blockage happening when launching a PyQt5 application implemented as the current GUI (on Ubuntu 18.04)

**Comment by FedeClaudi** [comment]
Thanks, for investigating and great solve!
Would you like to send a pull request with it?

**Comment by francesshei** [comment]
Yes sure!

**Comment by FedeClaudi** [comment]
Fixed by @francesshei  in https://github.com/brainglobe/brainrender/pull/166 and https://github.com/brainglobe/brainrender/pull/167
