### ISSUE TITLE
BUG: Failing to render entire cell

### ISSUE THREAD

**Issue by alice-muk** [brainglobe/brainrender#173]
I am rendering a series of swc files from a folder and a subset of the cells are not rendering entirely. It primarily seems to be an issue with long projections with dense arborizations at either end, and the axon between the two regions is missing.

I am using brainrender 2.0.2.9 and vedo 2021.0.2.

![17545_00129_top](https://user-images.githubusercontent.com/90416804/132745614-968e4388-7ad5-4a45-8b01-594f3849ee55.png)

File rendered in Vaa3d
![image](https://user-images.githubusercontent.com/90416804/132745837-9f7b1612-0653-4ca1-a64d-c65731ea2b6a.png)

**Comment by FedeClaudi** [comment]
Hi, 

The rendering of swc files in brainrender is a bit suboptimal at the moment. 
It's hard to say what the problem is without having the swc file though, would you be okay with sharing it?

**Comment by alice-muk** [comment]
Apologies for the delay. File included.

**Comment by alice-muk** [comment]
Apologies for the delay. Files included.
[br_example_scaled.zip](https://github.com/brainglobe/brainrender/files/7212998/br_example_scaled.zip)

**Comment by FedeClaudi** [comment]
Hey, I've had a look at the .swc file you've sent over. It looks fine to me (like the [one](https://github.com/brainglobe/brainrender/blob/master/examples/data/neuron1.swc) used in brainrender's examples), so I can't figure out what the problem is.

Under the hood brainrender uses [morphapi](https://github.com/brainglobe/morphapi/) to create meshes from .swc file and that, in turn, uses [NeuroM](https://github.com/BlueBrain/NeuroM) to parse the .swc: see [this line](https://github.com/brainglobe/morphapi/blob/3bb07bc80260b9a93cd98f5d073f7900065091b3/morphapi/morphology/morphology.py#L102).

I'm not sure if this is a brianrender/morphapi issue, I can't see why it should behave differently with your swc. Perhaps it's worth investigating if NeuroM is parsing it correctly. 

Do you have other .swc files for which the same issue occurs?
