### ISSUE TITLE
Allow camera distance to be fixed during Animation

### ISSUE THREAD

**Issue by blogeman** [brainglobe/brainrender#179]
The code below produces a nice video file moving from a sagittal view to a front view. However, the interpolation from the starting point to the ending point causes the camera to seemingly zoom in and zoom out. This is different from the zoom feature, but I'm lacking the vocabulary to describe the effect as anything else. My goal is to interpolate from camera_1 to camera_2 while maintaining a fixed camera distance from the focal point.

``` python

from brainrender import Scene, Animation
from rich import print
from myterial import orange
from pathlib import Path

print(f"[{orange}]Running example: {Path(__file__).name}")
"""
    This example shows how to create an animated video by specifying
    the camera parameters at a number of key frames
"""
# Set custom camera positions
camera_1 = {
    'pos': (7830, 4296, 36854),
    'viewup': (0, -1, 0),
    'clippingRange': (29305, 60266),
    'focalPoint': (7830, 4296, -5694),
    #'distance':
}
        
camera_2 = {
     'pos': (-50378, 4296, -5694),
     'viewup': (0, -1, 0),
     'clippingRange': (29305, 60266),
     'focalPoint': (7830, 4296, -5694),
     #'distance':
}

# Create a brainrender scene
scene = Scene(title="brain regions", inset=False)

# Add brain regions
scene.add_brain_region("TH")

anim = Animation(scene, "./examples", "vid4")

# Specify camera position and zoom at some key frames
anim.add_keyframe(0, camera=camera_1 , zoom=1)
anim.add_keyframe(2, camera=camera_2 , zoom=1)

# Make videos
anim.make_video(duration=3, fps=15)
```
In the above code the focal point, camera_1, and camera_2 all have the same value for the second axis (4296), so for this example axis 2 is constrained and I will ignore it from hereon out. Camera_1 and the focal point are aligned on axis 1, and camera_2 and the focal point are aligned on axis 3. Thus, the distance between the focal point and camera_1 should be exactly the same as the distance between the focal point and camera_2 (see figure below).  
![Capture](https://user-images.githubusercontent.com/62612214/143328362-8e6880f0-ce75-4dcc-8644-a72dafc04da9.PNG)

In the example code above the distance between the camera and the focal point is continuously changing during the interpolation between camera_1 and camera_2 and appears to be following the path in red. My guess is that this red path is being controlled by the 'interpol' parameter in the add_keyframe function https://github.com/brainglobe/brainrender/blob/a6e92db7135a67944f1e961ce52a8bcaa7d33f10/brainrender/video.py#L203-L212 which by default calls the sigma function https://github.com/brainglobe/brainrender/blob/a6e92db7135a67944f1e961ce52a8bcaa7d33f10/brainrender/video.py#L158-L167 
and could be altered by defining a different interpolation function, such as one that locks the distance between the camera and focal point. Am I on the right track?

Is there a way to fix the distance between the camera and focal point during interpolation?

**Comment by FedeClaudi** [comment]
Hey,

You're getting fancy with the animations, I love it!

I think the problems comes from the interpolation between the two camera parameters: 
https://github.com/brainglobe/brainrender/blob/a6e92db7135a67944f1e961ce52a8bcaa7d33f10/brainrender/video.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L370

The animation code is essentially doing a linear interpolation between each parameter of the two cameras (e.g. `pos`). So it should move from `camera_1` to `camera_2` along a straight line. The `sigma` interpolation doesn't actually change the trajectory, just the speed at which you move along it: at the start and end of the animation the transition will be slower, creating a smoother animation effect. The interpolation value `p` is in range `[0,1]` such that at `t=frame_0` it's `p=0` and the camera is like the first camera, while at `t=frame_1` it's `p=1` and the camera is like the second camera. The speed at which `p` changes defines the speed of the transition, as you can see below the slope of the sigmoid tapers towards `t=0` and `t=1`. 
Fancier animation softwares (like blender) allow you to define keyframes that act as control points for a bezier curve, then the bezier curve is the actual trajectory of the parameter (and, on top of that, you can move along it at different speeds). 


---
Anyways, this is besides the point you raised. The thing is, to get the animation you'd like, you need to interpolate between the two cameras differently. Conceptually, instead of sampling points along a line connecting the two camera values you want to sample points along the arc of a circle going through them and centered at the focal point (in 3D space). 
If you create a new class that subclasses `Animation` and define a new `_interpolate_cameras` method you can try to play around with different ways to interpolate between cameras, makes sense?

**Comment by marcomusy** [comment]
as a side note you may leverage the class `vedo.Arc` to compute points positions on an arc:
```python
from vedo import *
arc = Arc((7830, 4296, -5694), point1=(7830, 4296, 36854), point2=(-50378, 4296, -5694), res=100)
print(arc.points())
show(arc, axes=1)
```
![Screenshot from 2021-11-25 10-18-32](https://user-images.githubusercontent.com/32848391/143414122-ddea7970-a3ab-4221-a806-01ebb080caec.png)

**Comment by FedeClaudi** [comment]
Beautiful!

I think a great addition to the animation class would be to allow users to specify a path along which the camera should move, instead of interpolating between keyframes position. The path could be given by `Arc` like in this case or a spline (@marcomusy  is there spline computation in vedo?)

@blogeman I probably won't be adding this yet, since I'm not sure if a lot of people would be using it. But if you do end up making something that could be generally useful please feel free to submit a PR!

**Comment by marcomusy** [comment]
> is there spline computation in vedo?

yes it's called `Spline` :) 
e.g.: `Spline(points, easing="OutCubic")`

Check out example : `examples/simulations/spline_ease.py`

![ease](https://vedo.embl.es/images/simulations/spline_ease.gif)

**Comment by FedeClaudi** [comment]
`Vedo` is the best! It's such a rich library, great job!

@blogeman   perhaps one can use `Spline` and `Arc` to define fancy camera movements?

**Comment by blogeman** [comment]
Thanks, this is really useful info! I'm going to spend some time playing around and will let you know if I come up with anything that generally useful for other users.
