### ISSUE TITLE
Where can I find the example script for how to export a scene to .html?

### ISSUE THREAD

**Issue by JohannesWiesner** [brainglobe/brainrender#187]
**Describe the bug**

I wanted to try out an example script of how to export a scene to `.html` but the related link gives a 404 error

**To Reproduce**
1. Go to https://docs.brainrender.info/usage/videos-animations-and-exporting-to-html#exporting-to-html
2. Click on [embed in a website](https://fedeclaudi.github.io/scenes/regions.html)
3. See error

**Comment by FedeClaudi** [comment]
Hi,

Sorry the link is broken and we currently don't have an example of how to export a scene in our docs, but it's very simple.

You create and populate a `Scene` as you would normally, and then instead of calling `scene.render()` you call `scene.export("my/file.html")`, see [this](https://github.com/brainglobe/brainrender/blob/b414cebfc19a4ad8a230fe87eab6b68b562d3069/brainrender/render.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L283).

This is an example website where they used brainrender to create web visualizations: https://3dmousebrain.com/
