### ISSUE TITLE
Adding Mirrored Mesh as Actor Causes everything to disapear

### ISSUE THREAD

**Issue by gavinkress** [brainglobe/brainrender#196]
Hello Brainrender Authors, 

Thank you for a great library. I am trying to create a human brain with both hemispheres, the way I am apporaching this is to mirror the meshes created from each region and adding these mirrored meshes as separate actors with different colors (in the end each region will have a different color based on a weight mapping). Before adding these actors to the scene everything works great, but adding them causes everything except the axes to disapear from my scene.  Thank you so much for your help. 

```
import numpy
import brainrender
from brainrender import Scene
import vedo
import pandas as pd


vedo.settings['notebookBackend'] = 'k3d'
#brainrender.settings.SHOW_AXES = False
brainrender.settings.WHOLE_SCREEN = False
scene = Scene(atlas_name="allen_human_500um",  title='Brain', inset=False)

mesh = vedo.Mesh(scene.renderables[-1:])
mesh = mesh.mirror()
scene.add(mesh)


brain_regions = ["SubTH", "FrO", "H", "MV"]


for br in brain_regions:
    scene.add_brain_region(br, color="#4123fc", alpha=0.5)
    mesh = vedo.Mesh(scene.renderables[-1:])
    mesh = mesh.mirror()
    scene.add(mesh, color="#26f00e", alpha=0.5)


scene.render()
vedo.show(scene.renderables)

```

**Comment by marcomusy** [comment]
Hi @gavinkress 
what vedo version are you using? this line
`vedo.settings['notebookBackend'] = 'k3d'`
makes me think that you are using the latest one but `brainrender` supports a slightly older version, if that's the case try
`pip install vedo==2021.0.5`

**Comment by gavinkress** [comment]
@marcomusy Thank you for pointing this out, I downgraded my vedo, but now the vedo UI crashes after loading the renderables. It still does this even without the mirrored meshes.

**Comment by gavinkress** [comment]
@marcomusy I just tried it on a Mac and it is not crashing (still crashing on windows), but is not showing the mirrored regions

**Comment by FedeClaudi** [comment]
Hi, 

The human atlas was a first attempt to generate a human atlas in BG. As you can see below it's the only BG atlas still in version `<1`, and that's because beyond our initial effort we didn't see much interest in it and so we didn't continue to work on it.
![image](https://user-images.githubusercontent.com/17436313/156753740-794f613d-f7a1-4a7e-988f-a3477f59c76d.png)

If you inspect the meshes in the atlas in more details, you might notice a few things are off (e.g., the meshes's origin and so on). One of the consequences is that mirroring is not giving you the result you'd expect. I might be wrong but I'm quite sure this is the source of the problem, the same code with a different atlas should give you the result you'd like. 
Note also that you might want to more precisely determine along which direction to mirror meshes and with respect to what point. 

Finally, atlases are generally not symmetric. I'm not sure why Allen only released a half-brain atlas, but I'm not sure that simply mirrorirng it the best way to go. 


P.s.: internally in brainglobe there was some interested in fixing the human atlas up, but I'm not sure if this has progress very much. If you'd like to work on improving the atlas we can add you to our slack and we can help you do that, perhaps coordinating with other people potentially interested.
