### ISSUE TITLE
[BUG] Memory issue with loading .tif files into BrainRender

### ISSUE THREAD

**Issue by c3rry** [brainglobe/brainrender#379]
**Describe the bug**
We are receiving the error:  ERROR: MemoryError: Unable to allocate 262. GiB for an array with shape (35109336405,) and data type float64 when trying to plot a tiff file against the Allen Mouse Brain Atlas using Spyder
It also does not seem to be using virtual memory

**To Reproduce**
Implement the user_volumetric_data.py file with a .tif file, our .tif file contained 1827 frames and was of size 130 GB

**Expected behaviour**
Our data volume should have been plotted against the Allen Mouse Brain Atlas.

**Log file**
Please attach the l
[brainrender(8_26_24).txt](https://github.com/user-attachments/files/16753782/brainrender.8_26_24.txt)

**Computer used (please complete the following information):**

- OS: [Windows 10]
- Version [21H2]
- Hardware specs [e.g. 256 GB RAM, AMD Ryzen Threadripper PRO 5955WX 16-Cores CPU].

**Comment by adamltyson** [comment]
Hi @c3rry, 

I assume this is happening because the example creates a copy of your data to reorient your data to the atlas, and that requires more memory than you have. 

What are you trying to achieve with brainrender? The normal use case is to visualise data that has been aligned to an anatomical atlas, typically processed features (cell coordinates etc.). The method to visualise volumetric data is normally used for e.g. gene expression data.

If your data is 130GB, I assume it's raw data that hasn't been aligned to an atlas?

If you want to visualise raw volumetric data, I would recommend [napari](https://napari.org/stable/index.html), perhaps alongside the [napari brainrender plugin](https://brainglobe.info/tutorials/visualise-atlas-napari.html).

**Comment by adamltyson** [comment]
Hi @c3rry I'm going to close this now. Let us know if you have any further questions.
