### ISSUE TITLE
Help with visualising my own data with Brainrender + Allen atlas

### ISSUE THREAD

**Issue by Eddymorphling** [brainglobe/brainrender#381]
Hi Team,
This is not really a feature request of a bug. I am new to Brainrender and learning how to use it. 

I ran the entire `brainmapper` workflow and have brain registration and cell segmentation results `(points.npy)` from my datasets. A simple question, how do I display a 3D render of cell segmentation in a specific brain region on the Allen Brain atlas? Do I use this numpy array or do I need to covert any of the csv outputs into a numpy array for doing this (as mentioned [here](https://forum.image.sc/t/brainrender-pointsdensity-actor/98088)). Sorry for the very naive questions, quiet new to brainrender to be honest. Any help would be appreciated.

**Comment by adamltyson** [comment]
Hi @Eddymorphling,

If you have usage questions, the [image.sc forum](https://forum.image.sc/tag/brainglobe) is likely to be a better place to ask, there are more people there who can help you. Make sure to tag your post with `brainglobe` and the tool you're using (e.g. `brainrender`) so that the right people see it. 

However, I can give it a go. I assume you mean you want to visualise only the cells that are in specific brain region(s)? If so, this script should work. Hopefully it's obvious what needs to be changed, but let me know if you have any trouble. The resulting figure is at the bottom.

Script:
```python
from pathlib import Path

from brainrender.scene import Scene
from brainrender.actors import Points
from brainrender import settings

import numpy as np
settings.SHADER_STYLE = "plastic"
settings.SHOW_AXES = False

# set this to your brainmapper output .npy file
cells_path = Path("path/to/points.npy")

# Define regions of interest (easier to define all at the
# terminal/finest level of the hierarchy)
regions = ["VISp1", "VISp4", "VISp5"]

# Function to select specific regions
def get_cells_in_regions(scene, cells_path, regions):
    cells = np.load(cells_path)
    new_cells = []

    for cell in cells:
        if scene.atlas.structure_from_coords(cell, as_acronym=True, microns=True) in regions:
            new_cells.append(cell)

    new_cells = np.asarray(new_cells)

    return new_cells

# Create a brainrender scene
scene = Scene(title=f"brainmapper cells in {regions}", inset=False)

# Load points and select for those in specific regions
cells_points = get_cells_in_regions(scene, cells_path, regions)

# Create points actor
cells = Points(cells_points, radius=45, colors="palegoldenrod", alpha=0.8)

# Add cells
scene.add(cells)

# Add specific regions
for region in regions:
    scene.add_brain_region(region, color="mediumseagreen", alpha=0.2)

# Visualise brainrender scene
scene.render()

```

Result:
![brainmapper-regions](https://github.com/user-attachments/assets/1c03b22d-fe46-4a49-8a47-0cbed113f510)
