### ISSUE TITLE
using brain render for custom meshes 

### ISSUE THREAD

**Issue by anorak94** [brainglobe/brainrender#54]
hey i followed your advice to render a custom vtk object using brain render. But this is what my output looks like it doesnt get rendered at the correct location . I followed the code from the notebook

```
# We begin by adding the current path to sys.path to make sure that the imports work correctly
import sys
sys.path.append('../')
import os

# Set up VTKPLOTTER to work in Jupyter notebooks
from vtkplotter import *
embedWindow(backend=False) 

# Imports from brainrender
from brainrender.scene import Scene
from brainrender.Utils.ABA.connectome import ABA

# Before populating the scene, we need to change the current working directory to the parent folder, 
# then we are ready to start!
os.chdir(os.path.normpath(os.path.join(os.getcwd(), os.pardir)))

tutorial_scene = Scene(jupyter=True)
tutorial_scene.add_from_file("test_cerebellum.vtk")
tutorial_scene.render()

```

<img width="2048" alt="Screenshot 2020-04-18 at 14 46 28" src="https://user-images.githubusercontent.com/45297533/79638001-8a58dd80-8183-11ea-9359-2846e8890349.png">

**Comment by FedeClaudi** [comment]
continuing discussion in: https://github.com/BrancoLab/BrainRender/issues/53

Hi, it would have been better to keep this discussion under the previous issue since it's about the same problem. 
Also when opening an issue it would helpful if you could describe a bit your setup (e.g. OS, python version, brainrender version etc..). 

Anyway, the meshes from the allen brain atlas are specified in the coordinates frame of the allen atlas. Depending on how you generated `test-cerebellum.vtk` your mesh might not be defined in the same coordinates space. This means that you'll have to rotate and scale your mesh accordingly.

If this is not the problem, try updating brainrender to the latest version (0.3.4.2) with:
```
pip install brainrender --upgrade
```

Without knowing more about how you generated `test_cerebellum.vtk` there's not much more I can do.

**Comment by anorak94** [comment]
i generated it using itk snap and the volume was from allen brain

**Comment by FedeClaudi** [comment]
Allright. 

Depending on the resolution of the atlas you've used you'll need to scale the mesh up by some factor (see here for an example: https://github.com/BrancoLab/BrainRender/issues/44 ).
e.g. if you used a 10um resolution atlas, you'll have to multiply the coordinates of your mesh by a factor of 10. 

In addition to this it looks like you'll have to rotate and move around your mesh to match the coordinates space of the allen atlas. You can move the mesh by adding an offset to its coordinates. Each point in your mesh will be defined by three numbers, the coordinates `[x, y, z]`, if you want to move the mesh in the `x` direction by 100 you can adjust the coordinates so that thye'll be `[x+100, y, z]`. 

This is an example code to shift, rotate and scale an actor:

```
actor = tutorial_scene.add_from_file("test_cerebellum.vtk")
actor.translate(np.array([100, 0, 0]) # move by 100 in one direction
actor.Scale(2,1,1) # make it twice as large along one direction
actor.rotateX(90) # rotate by 90 degrees along x axis
```

You can find a list of methods to move/transform vtkplotter actors here: https://github.com/marcomusy/vtkplotter/blob/4a6c7e6216/vtkplotter/base.py

**Comment by anorak94** [comment]
wow thanks a lot ill try it. the tool is really cool ive been playing around with it and its amazing thanks for your help

**Comment by FedeClaudi** [comment]
No worries. Btw an easier fix might be to change the process you've used to create the mesh in the first place, but I don't know how itk snap works so I'm afraid I can't help. 

Good luck, will close for now but get in touch if you have other questions.

**Comment by anorak94** [comment]
do you know how i can create labelled meshes with allen brain ontology from volumetric data

**Comment by FedeClaudi** [comment]
I'm afraid not, sorry

**Comment by LSilvagnoli** [comment]
Hello @FedeClaudi 

can we still use vtkplotter methods to move/transform Volumetric actors in the last brainrender version ?
if yes, then in can't properly import vtkplotter methods and use them on user 3D objects.
if not, please let me know how i can adapt my non registered on allen atlas 3D objects to the render.

Thx

**Comment by FedeClaudi** [comment]
Hi, yeah it should all work correctly. What is not working for you? Can you give me more details about what you're trying to do and what the error/result is?

**Comment by LSilvagnoli** [comment]
Hi, Happy New Year !

i'm facing the same problem of having a custom mesh not placed on allen atlas.
i can render properly my object but can't use vtkplotter's methods to place it in my brain,since i canno't import it vtkplotter properly.

**Comment by FedeClaudi** [comment]
Hi, 

Can you give me more details about exactly what you're doing and what you're trying to achieve?
Some example code would be useful.

**Comment by LSilvagnoli** [comment]
![brnd](https://user-images.githubusercontent.com/95351758/148073691-d6ab8016-6150-48ba-aa3f-1f89a913ce9f.JPG)

Here is my scene, finally got to modify my mesh orientation.
Now my issue is to place this volume at the desired place in the root.render

use `actor.translate(np.array([100, 0, 0])`  give me this error 

> 'Mesh' object has no attribute 'translate'

`actor.Scale(2,1,1)
actor.rotateX(90)` work since i modify the way i use my python environment.

**Comment by marcomusy** [comment]
Try:
`actor.scale([2,1,1]).rotateX(90).shift([100,0,0])`

**Comment by FedeClaudi** [comment]
To move an actor, this should work: `actor.mesh.shift(dx=-232583.5, dy=-99691.5, dz=-188808.5)`, let me know!

Btw, ideally you'd have your data registered to the atlas prior to visualizing it with brainrender since manual alignment won't be very accurate.

**Comment by LSilvagnoli** [comment]
thanks @FedeClaudi @marcomusy 

`actor.shift([100,0,0])` works well !

@FedeClaudi should i align the slices first with brainreg before generate my custom volume ? can i generate custom volume within brainglobe workflow ?

**Comment by FedeClaudi** [comment]
Awesome, happy to know it worked. 

So if you have a 3D image you used to generate your data, you'll want to use [brainreg](https://github.com/brainglobe/brainreg) to register the data to the atlas. Then you can use the code/procedure you have to extract the mesh from the registered image, or [brainreg-manual](https://github.com/brainglobe/brainreg-segment) to manually segment it.
